namespace DTA.App.Shell;

/// <summary>1 trang hướng dẫn: tiêu đề, nhãn nhỏ, các mục (tên mục, nội dung).</summary>
public sealed record Guide(string Title, string Badge, (string Title, string Text)[] Sections);

/// <summary>Hướng dẫn của từng tab (khoá = mã tab). Chữ trong [ngoặc vuông] là tên nút trên giao diện.</summary>
public static class HelpGuides
{
    public static readonly IReadOnlyDictionary<string, Guide> All = new Dictionary<string, Guide>
    {
        ["esp"] = new("ESP - Xem vật thể trên bản đồ", "Xem bản đồ", [("Chức năng", "• Hiện tên và khoảng cách của điểm đào, mạch đá, côn trùng, đồ nhặt được ngay trên màn hình game.\n• Chỉ để xem, không điều khiển nhân vật nên bật cùng lúc với chức năng khác được."), ("Các nút & tùy chọn", "• [Bật ESP]: hiện / ẩn chữ trên màn hình game.\n• [Hiện khoảng cách]: ghi thêm số mét cạnh tên từng vật.\n• [Phạm vi]: chỉ hiện vật trong 30 m, 60 m quanh nhân vật, hoặc cả bản đồ.\n• [Nhóm]: chọn nhóm muốn xem: Cổ vật, Đá & quặng, Cây & nguyên liệu, Côn trùng, Thẻ.\n• [Cỡ chữ]: chữ trên màn hình game Nhỏ, Vừa, Lớn hoặc To.\n• Bảng [Loại đang có trên bản đồ]: bấm vào 1 dòng để hiện / ẩn riêng loại đó.\n• Bảng [Gần nhân vật nhất]: các vật gần nhất và cách bao nhiêu mét."), ("Lưu ý", "• Đừng thu nhỏ cửa sổ giả lập khi đang bật, chữ sẽ bị lệch.")]),
        ["fishing"] = new("Câu cá tự động", "Câu cá", [("Chức năng", "• Tự thả cần, chờ cá cắn, giật và kéo cá về; xong thì bảo quản hoặc bán nhanh theo ý bạn."), ("Các nút & tùy chọn", "• [ID cá] / [Bóng] / [Đã câu]: con cá đang cắn câu và số con đã câu được.\n• [Tự sửa cần]: cần hết độ bền thì tự sửa để câu tiếp.\n• [Có gói bán nhanh]: bật nếu tài khoản có gói bán nhanh, khi đó mới chọn được Bán nhanh.\n• [Sau khi câu được cá]: [Bảo quản] cho cá vào túi, [Bán nhanh] bán luôn.\n• [Lọc cá]: bật thì chỉ kéo cá đúng [ID cá], [Bóng], [Nền] đã chọn (mục nào không chọn thì lấy tất cả); cá khác tự thu cần sớm cho đỡ tốn độ bền. [Xoá điều kiện lọc] bỏ hết điều kiện lọc.\n• Thẻ giữ lại khi bán nhanh: [Giữ cá biến thể], [Giữ cá đột biến], [Giữ ID], [Giữ bóng], [Giữ nền] - cá khớp đủ các mục đã chọn thì được bảo quản; mục nào không chọn thì lấy tất cả, không chọn mục nào thì giữ hết. [Xoá điều kiện giữ] bỏ hết các điều kiện đó.\n• [Bật] / [Tắt]: bắt đầu / dừng câu.\n• [Cập nhật ID cá] (chân trang): tải lại danh sách ID cá mới nhất để biết bóng và nền của từng ID."), ("Cách dùng", "1. Đưa nhân vật ra sát mép nước, cầm cần câu.\n2. Chọn bảo quản hay bán nhanh, và cá muốn giữ / lọc.\n3. Bấm [Bật].")]),
        ["fishing_history"] = new("Lịch sử câu cá", "Lịch sử", [("Chức năng", "• Ghi lại mọi lượt đã làm được, mới nhất ở trên. Chữ mỗi dòng có màu theo nền của món."), ("Các nút & tùy chọn", "• [Ô tìm kiếm]: gõ ID hoặc tên cá để lọc nhanh.\n• [Bóng] / [Nền]: chỉ hiện cá đúng cỡ bóng / nền đã chọn.\n• [Xoá lịch sử]: xoá toàn bộ lịch sử của tab giả lập đang chọn.")]),
        ["excavation"] = new("Đào cổ vật", "Đào cổ vật", [("Chức năng", "• Tự đi tới điểm đào gần nhất, đào, nhận quà rồi sang điểm kế tiếp."), ("Các nút & tùy chọn", "• [Điểm đào] / [Cách điểm gần nhất] / [Đã đào]: số điểm đào trong tầm, khoảng cách tới điểm đang nhắm, số lần đã đào.\n• [Tự sửa xẻng]: xẻng hỏng thì tự sửa để đào tiếp.\n• [Lọc rương]: đào 1 nhát thấy không phải rương thì bỏ, đi tìm điểm khác.\n• [Phạm vi quanh chỗ đứng]: chỉ đi tới những chỗ cách nơi đứng lúc bấm Bật trong 30 m, 60 m, hoặc cả bản đồ.\n• [Tự động đổi map]: bản đồ đang đứng hết thì tự sang bản đồ khác.\n• [Các map được sang]: chọn những bản đồ được phép sang khi bật Tự động đổi map.\n• [Bật] / [Tắt]: bắt đầu / dừng."), ("Cách dùng", "1. Cầm xẻng trên tay.\n2. Chọn phạm vi và tùy chọn.\n3. Bấm [Bật].")]),
        ["lost_island"] = new("Đào Hòn đảo bị mất", "Hòn đảo bị mất", [("Chức năng", "• Luôn chọn điểm đào gần nhân vật nhất, chạy hết tốc 1 mạch tới đó (không đổi điểm giữa đường), tới nơi là đào luôn.\n• Tới nơi là bấm đào ngay, bấm dồn thật nhanh tới khi nút nhận quà hiện ra, bấm nhận rồi đi tiếp ngay.\n• Điểm đang chạy tới mà người khác đào trước thì bỏ ngay, sang điểm khác; không đào nhầm rương người khác.\n• Game báo đào hụt thì đi sát tâm điểm đào rồi đào lại; hụt 2 lần thì bỏ điểm đó."), ("Các nút & tùy chọn", "• [Điểm đào] / [Cách điểm gần nhất] / [Đã đào]: số điểm đào trên đảo, khoảng cách tới điểm đang nhắm, số lần đã đào.\n• [Tự sửa xẻng]: hết xẻng (kể cả giữa lúc đang đào rương) thì tự mua ngay gói xẻng mới bằng tiền sao rồi đào tiếp.\n• [Lọc rương]: tắt thì đào cả đá lẫn rương tới khi nhận quà. Bật thì chỉ bấm 1 nhát dò: không phải rương thì đi luôn, là rương thì đào tới khi nhận quà. Bật / tắt lúc đang chạy là có tác dụng ngay.\n• [Phạm vi quanh chỗ đứng]: 30 m, 60 m hoặc cả đảo.\n• [Bật] / [Tắt]: bắt đầu / dừng."), ("Cách dùng", "1. Vào Hòn đảo bị mất.\n2. Bật [Lọc rương] nếu chỉ muốn lấy rương.\n3. Bấm [Bật]."), ("Lưu ý", "• Để đủ tiền sao nếu bật [Tự sửa xẻng].\n• Mọi lần đào được ghi vào tab Lịch sử; quà là tiền sao thì ghi \"Tiền sao\".")]),
        ["excavation_history"] = new("Lịch sử đào", "Lịch sử", [("Chức năng", "• Ghi lại mọi lượt đã làm được, mới nhất ở trên. Chữ mỗi dòng có màu theo nền của món."), ("Các nút & tùy chọn", "• [Ô tìm kiếm]: gõ tên để lọc nhanh danh sách.\n• [Nền]: chỉ hiện các món thuộc nền đã chọn.\n• [Xoá lịch sử]: xoá toàn bộ lịch sử của tab giả lập đang chọn.")]),
        ["mining"] = new("Đập đá tự động", "Đập đá", [("Chức năng", "• Tự đi tới mạch đá gần nhất, đập lấy quặng rồi sang mạch kế tiếp."), ("Các nút & tùy chọn", "• [Điểm đập] / [Cách điểm gần nhất] / [Đã đập]: số điểm đập trong tầm, khoảng cách tới điểm đang nhắm, số lần đã đập.\n• [Tự sửa cuốc]: cuốc hỏng thì tự sửa để đập tiếp.\n• [Loại muốn đập]: [Tất cả], chỉ [Đá & quặng] hoặc chỉ [Quặng sự kiện].\n• [Phạm vi quanh chỗ đứng]: chỉ đi tới những chỗ cách nơi đứng lúc bấm Bật trong 30 m, 60 m, hoặc cả bản đồ.\n• [Tự động đổi map]: bản đồ đang đứng hết thì tự sang bản đồ khác.\n• [Các map được sang]: chọn những bản đồ được phép sang khi bật Tự động đổi map.\n• [Bật] / [Tắt]: bắt đầu / dừng."), ("Cách dùng", "1. Cầm cuốc trên tay.\n2. Chọn loại muốn đập và phạm vi.\n3. Bấm [Bật].")]),
        ["mining_history"] = new("Lịch sử đập đá", "Lịch sử", [("Chức năng", "• Ghi lại mọi lượt đã làm được, mới nhất ở trên. Chữ mỗi dòng có màu theo nền của món."), ("Các nút & tùy chọn", "• [Ô tìm kiếm]: gõ tên để lọc nhanh danh sách.\n• [Nền]: chỉ hiện các món thuộc nền đã chọn.\n• [Xoá lịch sử]: xoá toàn bộ lịch sử của tab giả lập đang chọn.")]),
        ["insect"] = new("Bắt bọ tự động", "Bắt bọ", [("Chức năng", "• Tự tìm côn trùng, rón rén lại gần rồi vung vợt bắt."), ("Các nút & tùy chọn", "• [Bọ trong tầm] / [Cách con gần nhất] / [Đã bắt]: số con trong tầm, khoảng cách tới con đang nhắm, số con đã bắt.\n• [Tự sửa vợt]: vợt hỏng thì tự sửa để bắt tiếp.\n• [Có gói bán nhanh]: bật nếu tài khoản có gói bán nhanh, khi đó mới chọn được Bán nhanh.\n• [Sau khi bắt được]: [Bảo quản] cho vào túi, [Bán nhanh] bán luôn.\n• [Giữ nền]: khi đang bán nhanh, con thuộc nền được chọn vẫn được bảo quản; không chọn nền nào thì giữ hết.\n• [Loại muốn bắt]: Côn trùng, Chim, Thẻ bay, Hộp sao, Hộp kim cương.\n• [Lọc bọ]: chỉ bắt con thuộc nền được chọn; không chọn nền nào thì nền nào cũng bắt.\n• [Phạm vi quanh chỗ đứng]: chỉ đi tới những chỗ cách nơi đứng lúc bấm Bật trong 30 m, 60 m, hoặc cả bản đồ.\n• [Tự động đổi map]: bản đồ đang đứng hết thì tự sang bản đồ khác.\n• [Các map được sang]: chọn những bản đồ được phép sang khi bật Tự động đổi map.\n• [Bật] / [Tắt]: bắt đầu / dừng."), ("Cách dùng", "1. Cầm vợt trên tay.\n2. Chọn loại muốn bắt và phạm vi.\n3. Bấm [Bật].")]),
        ["insect_history"] = new("Lịch sử bắt bọ", "Lịch sử", [("Chức năng", "• Ghi lại mọi lượt đã làm được, mới nhất ở trên. Chữ mỗi dòng có màu theo nền của món."), ("Các nút & tùy chọn", "• [Ô tìm kiếm]: gõ tên để lọc nhanh danh sách.\n• [Nền]: chỉ hiện các món thuộc nền đã chọn.\n• [Xoá lịch sử]: xoá toàn bộ lịch sử của tab giả lập đang chọn.")]),
        ["collect"] = new("Thu lượm tự động", "Thu lượm", [("Chức năng", "• Tự đi nhặt các món nằm dưới đất mà không cần dụng cụ."), ("Các nút & tùy chọn", "• [Đồ nhặt được] / [Cách món gần nhất] / [Đã nhặt]: số món trong tầm, khoảng cách tới món đang nhắm, số lần đã nhặt.\n• [Loại muốn nhặt]: Củi, Trứng, Nấm, Tôm, Rau củ, Thẻ.\n• [Phạm vi quanh chỗ đứng]: chỉ đi tới những chỗ cách nơi đứng lúc bấm Bật trong 30 m, 60 m, hoặc cả bản đồ.\n• [Tự động đổi map]: bản đồ đang đứng hết thì tự sang bản đồ khác.\n• [Các map được sang]: chọn những bản đồ được phép sang khi bật Tự động đổi map.\n• [Bật] / [Tắt]: bắt đầu / dừng."), ("Cách dùng", "1. Chọn loại muốn nhặt và phạm vi.\n2. Bấm [Bật].")]),
        ["collect_history"] = new("Lịch sử thu lượm", "Lịch sử", [("Chức năng", "• Ghi lại mọi lượt đã làm được, mới nhất ở trên. Chữ mỗi dòng có màu theo nền của món."), ("Các nút & tùy chọn", "• [Ô tìm kiếm]: gõ tên để lọc nhanh danh sách.\n• [Nền]: chỉ hiện các món thuộc nền đã chọn.\n• [Xoá lịch sử]: xoá toàn bộ lịch sử của tab giả lập đang chọn.")]),
        ["teleport"] = new("Dịch chuyển", "Dịch chuyển", [("Chức năng", "• Xem nhân vật đang ở bản đồ nào, tọa độ nào và lưu lại các vị trí bạn hay tới."), ("Các nút & tùy chọn", "• [Vị trí nhân vật]: bản đồ và tọa độ hiện tại, đọc thẳng từ game.\n• [Tên vị trí]: đặt tên cho vị trí; để trống thì tool tự đặt.\n• [Lưu vị trí hiện tại]: lưu chỗ nhân vật đang đứng.\n• [Lưu sửa đổi]: lưu tên / tọa độ vừa sửa của vị trí đang chọn.\n• [Xoá vị trí]: xoá vị trí đang chọn.\n• Bảng vị trí: bấm 1 dòng để chọn vị trí đó. Cột Cách đây là khoảng cách tới vị trí cùng bản đồ; vị trí ở bản đồ khác hiện chữ mờ.")]),
        ["settings"] = new("Cài đặt", "Cài đặt", [("Các nút & tùy chọn", "• [Ghi nhớ cài đặt]: bật thì mọi tùy chọn bạn đã chỉnh được giữ cho lần mở tool sau; tắt thì mỗi lần mở tool, tùy chọn trở về mặc định. Lịch sử và vị trí đã lưu luôn được giữ."), ("Thanh trên cùng (mọi trang)", "• [Giả lập] / [Tab]: chọn giả lập và tab giả lập đang chơi.\n• [↻]: tìm lại các tab giả lập đang mở.\n• [Ghim trên cùng]: giữ cửa sổ tool luôn nằm trên các cửa sổ khác.\n• [?]: mở hướng dẫn của trang đang xem.\n• [Đăng xuất key]: thoát key đang dùng để nhập key khác.")]),
        ["upcoming-monster-0"] = new("Quái vật", "Sắp có", [("Chức năng", "• Đang phát triển, sẽ có ở bản cập nhật sau.")]),
    };
}
